name: Build and Deploy Web App

# source: https://gist.github.com/rodydavis/bde9a9a8c2fcdcf3474c0f50248f2e3a

on:
  push:
    branches:
      - master

jobs:

  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.conclusion }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - 'app/**'
  
    - id: early
      name: Check for any changes in app/ folder
      run: if [[ ${{steps.changes.outputs.src}} == false ]]; then exit 1 ; fi

  build_web:
    needs: check
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
        
    if: needs.check.outputs.status == 'success'
    steps:
    - uses: actions/checkout@v1
    - run: ls -lah
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter config --enable-web
    - run: flutter build web --base-href /flutter-notes/ --dart-define=DB_BASE_URL=https://flutter-notes.herokuapp.com/
    - run: ls -lah
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: app/build/web # The folder the action should deploy.
